version: "3"
services:
 django_server:
  container_name: drf-test-project-container
  build: .
  ports:
   - "8000:8000"
  volumes:
   - ./:/app/
  command: bash -c "poetry config virtualenvs.create true && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

