# Generated by Django 5.1.2 on 2024-10-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='just_a_temp',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
