# Generated by Django 5.1.2 on 2024-10-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_just_a_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='just_a_temp',
        ),
    ]
