# Generated by Django 5.1.2 on 2024-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_restaurant_id_restaurant_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
