# Generated by Django 5.1.2 on 2024-10-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurant_restaurant_id_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
