# Generated by Django 5.1.2 on 2024-10-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizza_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='dough_type',
            field=models.CharField(choices=[('THIN', 'THIN'), ('THICK', 'THICK')], default='THICK', max_length=50),
        ),
    ]
