# Generated by Django 5.1.2 on 2024-10-21 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_alter_pizza_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
